### ISSUE TITLE
Fix README.md paths

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/lstrachan_honeybee_relatedness#13]
@LStrachan 

`README.md` describes `SimulateFounderPop.R`, `YearCycle_Relatedness.R`, and `Plot_YearCycle_output.R`, while these sit in `YearCycleSimulation`, which has `Scripts` and `PlottingData`. So, adapt to something like:

`YearCycleSimulation` contains `Scripts` and `PlottingData`.

`Scripts` contains:
* `Script1` bla bla
* `Script2` bla bla
* `Script3` bla bla

`PlottingData` contains:
* `XYZ1` bla bla
* `XYZ2` bla bla

Write these README files like you are writing it for a dummy - because people spent very little time on parsing such files so we want to be explicit where is what;)

**Comment by LStrachan** [comment]
All edited now
